### ISSUE TITLE
Errors while reading with latest lucee versions

### ISSUE THREAD

**Issue by pscheit** [lucee/extension-mongodb#9]
Hi there,

thank you so much for this extension! I just updated from 4.5 to 5.1

Here is my stack
![image](https://cloud.githubusercontent.com/assets/488189/25469718/41fd89f0-2b1e-11e7-97b5-aa899bfeb419.png)

When I use the extension and save a struct in the cache I get the following error:

```
Message	java.lang.ClassNotFoundException: lucee.runtime.type.StructImpl
Cause	java.lang.RuntimeException
Stacktrace	The Error Occurred in
/vagrant/webroot/coldbox/system/cache/providers/RailoProvider.cfc: line 254 
252: }
253: else{
254: return cacheGet( arguments.objectKey, true, getConfiguration().cacheName );
255: }
256: }
```

```
Java Stacktrace	lucee.runtime.exp.NativeException: java.lang.ClassNotFoundException: lucee.runtime.type.StructImpl
 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 	at org.apache.felix.framework.BundleWiringImpl.doImplicitBootDelegation(BundleWiringImpl.java:1765)
 	at org.apache.felix.framework.BundleWiringImpl.searchDynamicImports(BundleWiringImpl.java:1700)
 	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1536)
 	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
 	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1998)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 	at java.lang.Class.forName0(Native Method)
 	at java.lang.Class.forName(Class.java:348)
 	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
 	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
 	at org.lucee.mongodb.util.SerializerUtil.evaluate(SerializerUtil.java:50)
 	at org.lucee.mongodb.cache.MongoDBCacheDocument.getValue(MongoDBCacheDocument.java:33)
 	at org.lucee.mongodb.cache.MongoDBCacheDocument.getValue(MongoDBCacheDocument.java:29)
 	at org.lucee.mongodb.cache.MongoDBCacheEntry.getValue(MongoDBCacheEntry.java:40)
 	at org.lucee.mongodb.cache.MongoDBCache.getValue(MongoDBCache.java:187)
 	at lucee.runtime.functions.cache.CacheGet._call(CacheGet.java:96)
 	at lucee.runtime.functions.cache.CacheGet.call(CacheGet.java:89)
 	at system.cache.providers.railoprovider_cfc$cf.udfCall3(/coldbox/system/cache/providers/RailoProvider.cfc:254)
 	at system.cache.providers.railoprovider_cfc$cf.udfCall(/coldbox/system/cache/providers/RailoProvider.cfc)
 	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
 	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:338)
 	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:225)
 	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697)
 	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)
 	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
 	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:755)
 	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1697)
```

do i need to use another provider?

**Comment by pscheit** [comment]
my bad I just need to use another coldbox provider and i works.. sorry

**Comment by pscheit** [comment]
sorry, the problem persists. Can I help to fix?

**Comment by sjdaniels** [comment]
The cache implementation was put together before I got involved and we are aware that it does not work with complex variables. Dates, Struct, Array. See issue #4.

If you want to take a crack at fixing it feel free to fork and send us a pull request.

**Comment by sjdaniels** [comment]
This appears to be fixed in the master branch and the version on the extension provider, can you confirm?
